# Generated by Django 4.2.16 on 2024-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="author_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
