# Generated by Django 4.2.16 on 2024-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_comment_author_comment_author_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author_name",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
